#!/usr/bin/env python3
"""Generate the active findings report from its canonical structured source."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "findings-and-implications.json"
OUTPUT = ROOT / "FINDINGS_AND_STRATEGIC_IMPLICATIONS.md"


def md(value):
    return str(value or "").replace("|", "\\|").strip()


def evidence_links(ids):
    if not ids:
        return "`Insufficient Evidence`"
    return ", ".join(
        f"[{evidence_id}](SUBSTITUTE_EVIDENCE_REGISTER.md#{evidence_id})"
        for evidence_id in ids
    )


def market_refs(refs):
    if not refs:
        return ""
    rendered = ", ".join(f"`{ref}`" for ref in refs)
    return f" Market-research trace: {rendered} in `data/market-research.json`."


def trace(item):
    return (
        f"Evidence: {evidence_links(item.get('evidence_ids', []))}."
        + market_refs(item.get("market_research_refs", []))
    )


def bullets(items):
    return "\n".join(f"- {md(item)}" for item in items)


def build(data):
    meta = data["meta"]
    executive = data["executive_conclusion"]
    parts = [
        "# Findings & Strategic Implications",
        "",
        "> Generated from `data/findings-and-implications.json`. Do not edit this file manually.",
        "> This is the active research conclusion layer. Historical strategic hypotheses remain archived and are not current recommendations.",
        "",
        f"**Status:** `{md(meta['status'])}`",
        f"**Last reviewed:** `{md(meta['last_reviewed'])}`",
        f"**Decision boundary:** {md(meta['decision_boundary'])}",
        "",
        "## 1. Executive conclusion",
        "",
        f"### {md(executive['headline'])}",
        "",
        md(executive["summary"]),
        "",
        f"**Current decision:** `{md(executive['current_decision'])}`",
        f"**Confidence:** `{md(executive['confidence'])}`",
        trace(executive),
        "",
        "## 2. Conclusions by Job-to-be-Done",
        "",
    ]
    for job in data["jobs"]:
        parts.extend(
            [
                f"### {md(job['title'])}",
                "",
                f"- **Dominant current workflow:** {md(job['dominant_current_workflow'])}",
                f"- **Most relevant researched competitors:** {', '.join(f'`{slug}`' for slug in job['competitor_slugs'])}. This is a relevance set, not a numeric ranking.",
                f"- **Strongest substitute patterns:** {', '.join(f'`{sid}`' for sid in job['substitute_ids'])}.",
                f"- **Main trust mechanism:** {md(job['main_trust_mechanism'])}",
                f"- **Supported advantages:** {md(job['supported_advantages'])}",
                f"- **Supported weaknesses:** {md(job['supported_weaknesses'])}",
                f"- **Evidence quality:** {md(job['evidence_quality'])}",
                f"- **Unresolved questions:** {md(job['unresolved_questions'])}",
                f"- **Confidence:** `{md(job['confidence'])}`",
                f"- {trace(job)}",
                "",
            ]
        )

    parts.extend(["## 3. Cross-market findings", ""])
    for item in data["cross_market_findings"]:
        parts.extend(
            [
                f"### {md(item['finding'])}",
                "",
                md(item["interpretation"]),
                "",
                f"**Confidence:** `{md(item['confidence'])}`",
                trace(item),
                "",
            ]
        )

    parts.extend(["## 4. Strongest competitive pressures", ""])
    for item in data["competitive_pressures"]:
        parts.extend(
            [
                f"### {md(item['pressure'])}",
                "",
                md(item["why_it_matters"]),
                "",
                f"Linked substitutes: {', '.join(f'`{sid}`' for sid in item['substitute_ids'])}.",
                f"Confidence: `{md(item['confidence'])}`.",
                trace(item),
                "",
            ]
        )

    def assumption_section(title, items):
        section = [title, ""]
        for item in items:
            section.extend(
                [
                    f"### {md(item['assumption'])}",
                    "",
                    f"- **Supporting evidence:** {md(item['supporting_evidence'])}",
                    f"- **Counterevidence:** {md(item['counterevidence'])}",
                    f"- **Confidence:** `{md(item['confidence'])}`",
                    f"- **Still unproven:** {md(item['unproven'])}",
                    f"- {trace(item)}",
                    "",
                ]
            )
        return section

    parts.extend(
        assumption_section(
            "## 5. BizMatch assumptions that gained support",
            data["assumptions_strengthened"],
        )
    )
    parts.extend(
        assumption_section(
            "## 6. BizMatch assumptions that weakened",
            data["assumptions_weakened"],
        )
    )

    parts.extend(
        [
            "## 7. Supported pains versus hypotheses",
            "",
            "| Pain | Evidence status | Trace | Caveat |",
            "| --- | --- | --- | --- |",
        ]
    )
    for item in data["pains"]:
        market = market_refs(item.get("market_research_refs", []))
        market_cell = f" {md(market)}" if market else ""
        parts.append(
            f"| {md(item['pain'])} | `{md(item['status'])}` | "
            f"{evidence_links(item.get('evidence_ids', []))}{market_cell} | "
            f"{md(item['caveat'])} |"
        )

    boundaries = data["conclusion_boundaries"]
    parts.extend(
        [
            "",
            "## 8. What can and cannot be concluded",
            "",
            "### Justified by current evidence",
            "",
            bullets(boundaries["justified"]),
            "",
            "### Plausible but unverified",
            "",
            bullets(boundaries["plausible_unverified"]),
            "",
            "### Prohibited by insufficient evidence",
            "",
            bullets(boundaries["prohibited"]),
            "",
            "## 9. Customer Discovery agenda",
            "",
            "| Priority | Job | Research question | Decision link |",
            "| --- | --- | --- | --- |",
        ]
    )
    for item in data["customer_discovery"]:
        parts.append(
            f"| `{md(item['priority'])}` | `{md(item['job_id'])}` | "
            f"{md(item['question'])} | {md(item['decision_link'])} |"
        )

    parts.extend(["", "## 10. Conditional strategic implications", ""])
    for item in data["conditional_implications"]:
        parts.extend(
            [
                f"### Evidence observed: {md(item['evidence_observed'])}",
                "",
                f"- **Implication if confirmed:** {md(item['implication_if_confirmed'])}",
                f"- **Risk of acting too early:** {md(item['risk_of_acting_too_early'])}",
                f"- **Validation needed:** {md(item['validation_needed'])}",
                f"- **Confidence:** `{md(item['confidence'])}`",
                f"- {trace(item)}",
                "",
            ]
        )

    parts.extend(["## Required Red Team assessment", ""])
    for item in data["red_team"]:
        parts.extend(
            [
                f"### {md(item['id'])} — {md(item['possibility'])}",
                "",
                f"- **Supporting evidence:** {md(item['supporting_evidence'])}",
                f"- **Counterevidence:** {md(item['counterevidence'])}",
                f"- **Unknowns:** {md(item['unknowns'])}",
                f"- **Current confidence:** `{md(item['confidence'])}`",
                f"- **Customer Discovery test:** {md(item['customer_discovery_test'])}",
                f"- **Trace:** {evidence_links(item.get('evidence_ids', []))}",
                "",
            ]
        )

    parts.extend(
        [
            "## Methodology and evidence limitations",
            "",
            bullets(data["methodology_limitations"]),
            "",
            "## Canonical traceability",
            "",
            "- Competitors: `data/competitive-research-tracker.csv`.",
            "- Substitute entities: `data/substitutes-research.csv`.",
            "- Claim-level evidence: `data/substitute-evidence.csv`.",
            "- Job-stage workflows: `data/substitute-workflows.csv`.",
            "- Aggregate market-research assessment: `data/market-research.json`.",
            "- Active conclusions: `data/findings-and-implications.json`.",
            "",
        ]
    )
    return "\n".join(parts)


def main():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    OUTPUT.write_text(build(data), encoding="utf-8")
    print(f"Generated {OUTPUT.name} from {SOURCE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
