#!/usr/bin/env python3
"""Generate Phase 1 substitute matrix, workflows, and evidence register."""

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUBSTITUTES_PATH = ROOT / "data" / "substitutes-research.csv"
EVIDENCE_PATH = ROOT / "data" / "substitute-evidence.csv"
WORKFLOWS_PATH = ROOT / "data" / "substitute-workflows.csv"

JOB_LABELS = {
    "JOB-COFOUNDER": "Founder seeking a co-founder",
    "JOB-FOUNDER-INVESTOR": "Founder seeking an investor",
    "JOB-INVESTOR-SOURCING": "Investor sourcing startups or founders",
    "JOB-TRUSTED-PROGRESSION": "Founder and investor progressing to trusted interaction",
}


def read_rows(path):
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def md(value):
    return (value or "").replace("|", "<br>").replace("\n", " ").strip()


def link(url, title):
    return f"[{md(title)}]({url})" if url else "Unverified"


def build_matrix(substitutes):
    rows = []
    for row in substitutes:
        evidence_quality = row["source_type"] or "Unverified"
        rows.append(
            "| "
            + " | ".join(
                (
                    md(row["name"]),
                    md(row["category"]),
                    md(row["classification"]),
                    md(row["target_persona"]),
                    md(row["job_to_be_done"]),
                    md(row["workflow_stages_covered"]),
                    md(row["advantages"]),
                    md(row["limitations"]),
                    md(row["trust_mechanism"]),
                    md(row["switching_cost"]),
                    md(row["substitute_strength"]),
                    md(evidence_quality),
                    md(row["confidence"]),
                )
            )
            + " |"
        )
    return """# Substitute Matrix

> Generated from `data/substitutes-research.csv`. Do not edit this file manually.
> Strength is qualitative and evidence-constrained; no numeric threat score is used.

| Substitute | Category | Classification | Persona | Job | Stages covered | Main advantage | Main limitation | Trust mechanism | Switching cost | Strength | Evidence quality | Confidence |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
""" + "\n".join(rows) + "\n"


def build_workflows(workflows):
    grouped = defaultdict(list)
    for row in workflows:
        grouped[row["job_id"]].append(row)

    parts = [
        "# Substitute Workflow Maps",
        "",
        "> Generated from `data/substitute-workflows.csv`. Do not edit this file manually.",
        "> Each Job is mapped separately. `Unverified` and `Insufficient Evidence` are preserved.",
        "",
    ]
    for job_id in JOB_LABELS:
        parts.extend(
            [
                f"## {JOB_LABELS[job_id]}",
                "",
                "| Stage | Current action | Tools / channels | People | Manual work | Time / friction | Trust requirement | Current advantage | Current limitation | Evidence | Status | Confidence |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for row in sorted(grouped[job_id], key=lambda item: int(item["stage_order"])):
            parts.append(
                "| "
                + " | ".join(
                    (
                        f"{row['stage_order']}. {md(row['stage_id'])}",
                        md(row["current_action"]),
                        md(row["tools_channels"]),
                        md(row["people_involved"]),
                        md(row["manual_work"]),
                        md(row["time_or_friction"]),
                        md(row["trust_requirement"]),
                        md(row["current_advantage"]),
                        md(row["current_limitation"]),
                        md(row["evidence_ids"]) or "None recorded",
                        md(row["evidence_status"]),
                        md(row["confidence"]),
                    )
                )
                + " |"
            )
        parts.append("")
    return "\n".join(parts)


def build_evidence_register(evidence):
    parts = [
        "# Substitute Evidence Register",
        "",
        "> Generated from `data/substitute-evidence.csv`. Do not edit this file manually.",
        "> A source can establish that a solution exists without establishing adoption, effectiveness, satisfaction, demand for an alternative, or willingness to pay.",
        "",
    ]
    for row in evidence:
        parts.extend(
            [
                f"## {row['evidence_id']} — {row['claim_type']}",
                "",
                f"- Claim: {row['claim']}",
                f"- Evidence dimension: `{row['evidence_dimension']}`",
                f"- Source: {link(row['source_url'], row['source_title'])}",
                f"- Source date: {row['source_date'] or 'Not recorded'}",
                f"- Last verified: {row['last_verified']}",
                f"- Source type: `{row['source_type']}`",
                f"- Supporting summary: {row['supporting_excerpt_or_summary']}",
                f"- Confidence: `{row['confidence']}`",
                f"- Limitation: {row['limitation']}",
                f"- Linked substitute IDs: `{row['substitute_id'] or 'None — cross-cutting limitation'}`",
                f"- Linked Jobs: `{row['job_id']}`",
                "",
            ]
        )
    return "\n".join(parts)


def main():
    substitutes = read_rows(SUBSTITUTES_PATH)
    evidence = read_rows(EVIDENCE_PATH)
    workflows = read_rows(WORKFLOWS_PATH)
    (ROOT / "SUBSTITUTE_MATRIX.md").write_text(build_matrix(substitutes), encoding="utf-8")
    (ROOT / "SUBSTITUTE_WORKFLOWS.md").write_text(build_workflows(workflows), encoding="utf-8")
    (ROOT / "SUBSTITUTE_EVIDENCE_REGISTER.md").write_text(
        build_evidence_register(evidence),
        encoding="utf-8",
    )
    print(
        f"Generated substitute reports from {len(substitutes)} substitutes, "
        f"{len(evidence)} evidence records, and {len(workflows)} workflow stages"
    )


if __name__ == "__main__":
    main()
